/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiReportsPdfRouteImport } from './routes/api/reports/pdf'
import { Route as ApiPublicHooksCleanupLogsRouteImport } from './routes/api/public/hooks/cleanup-logs'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsPdfRoute = ApiReportsPdfRouteImport.update({
  id: '/api/reports/pdf',
  path: '/api/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupLogsRoute =
  ApiPublicHooksCleanupLogsRouteImport.update({
    id: '/api/public/hooks/cleanup-logs',
    path: '/api/public/hooks/cleanup-logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/settings'
    | '/watchlist'
    | '/api/config'
    | '/api/health'
    | '/api/records'
    | '/api/reports/pdf'
    | '/api/public/hooks/cleanup-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/settings'
    | '/watchlist'
    | '/api/config'
    | '/api/health'
    | '/api/records'
    | '/api/reports/pdf'
    | '/api/public/hooks/cleanup-logs'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/settings'
    | '/watchlist'
    | '/api/config'
    | '/api/health'
    | '/api/records'
    | '/api/reports/pdf'
    | '/api/public/hooks/cleanup-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiReportsPdfRoute: typeof ApiReportsPdfRoute
  ApiPublicHooksCleanupLogsRoute: typeof ApiPublicHooksCleanupLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/pdf': {
      id: '/api/reports/pdf'
      path: '/api/reports/pdf'
      fullPath: '/api/reports/pdf'
      preLoaderRoute: typeof ApiReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-logs': {
      id: '/api/public/hooks/cleanup-logs'
      path: '/api/public/hooks/cleanup-logs'
      fullPath: '/api/public/hooks/cleanup-logs'
      preLoaderRoute: typeof ApiPublicHooksCleanupLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiReportsPdfRoute: ApiReportsPdfRoute,
  ApiPublicHooksCleanupLogsRoute: ApiPublicHooksCleanupLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
