/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevLogsRouteImport } from './routes/dev.logs'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiScraperLogsStreamRouteImport } from './routes/api/scraper-logs.stream'
import { Route as ApiReportsPdfRouteImport } from './routes/api/reports/pdf'
import { Route as ApiDevAuthRouteImport } from './routes/api/dev/auth'
import { Route as ApiPublicHooksCleanupLogsRouteImport } from './routes/api/public/hooks/cleanup-logs'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogsRoute = DevLogsRouteImport.update({
  id: '/dev/logs',
  path: '/dev/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScraperLogsStreamRoute = ApiScraperLogsStreamRouteImport.update({
  id: '/api/scraper-logs/stream',
  path: '/api/scraper-logs/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsPdfRoute = ApiReportsPdfRouteImport.update({
  id: '/api/reports/pdf',
  path: '/api/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevAuthRoute = ApiDevAuthRouteImport.update({
  id: '/api/dev/auth',
  path: '/api/dev/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupLogsRoute =
  ApiPublicHooksCleanupLogsRouteImport.update({
    id: '/api/public/hooks/cleanup-logs',
    path: '/api/public/hooks/cleanup-logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/database': typeof DatabaseRoute
  '/jobs': typeof JobsRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/version': typeof ApiVersionRoute
  '/dev/logs': typeof DevLogsRoute
  '/api/dev/auth': typeof ApiDevAuthRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/scraper-logs/stream': typeof ApiScraperLogsStreamRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/database': typeof DatabaseRoute
  '/jobs': typeof JobsRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/version': typeof ApiVersionRoute
  '/dev/logs': typeof DevLogsRoute
  '/api/dev/auth': typeof ApiDevAuthRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/scraper-logs/stream': typeof ApiScraperLogsStreamRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/database': typeof DatabaseRoute
  '/jobs': typeof JobsRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/version': typeof ApiVersionRoute
  '/dev/logs': typeof DevLogsRoute
  '/api/dev/auth': typeof ApiDevAuthRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/scraper-logs/stream': typeof ApiScraperLogsStreamRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/database'
    | '/jobs'
    | '/records'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/api/config'
    | '/api/health'
    | '/api/records'
    | '/api/version'
    | '/dev/logs'
    | '/api/dev/auth'
    | '/api/reports/pdf'
    | '/api/scraper-logs/stream'
    | '/api/public/hooks/cleanup-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/database'
    | '/jobs'
    | '/records'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/api/config'
    | '/api/health'
    | '/api/records'
    | '/api/version'
    | '/dev/logs'
    | '/api/dev/auth'
    | '/api/reports/pdf'
    | '/api/scraper-logs/stream'
    | '/api/public/hooks/cleanup-logs'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/database'
    | '/jobs'
    | '/records'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/api/config'
    | '/api/health'
    | '/api/records'
    | '/api/version'
    | '/dev/logs'
    | '/api/dev/auth'
    | '/api/reports/pdf'
    | '/api/scraper-logs/stream'
    | '/api/public/hooks/cleanup-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  DatabaseRoute: typeof DatabaseRoute
  JobsRoute: typeof JobsRoute
  RecordsRoute: typeof RecordsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiVersionRoute: typeof ApiVersionRoute
  DevLogsRoute: typeof DevLogsRoute
  ApiDevAuthRoute: typeof ApiDevAuthRoute
  ApiReportsPdfRoute: typeof ApiReportsPdfRoute
  ApiScraperLogsStreamRoute: typeof ApiScraperLogsStreamRoute
  ApiPublicHooksCleanupLogsRoute: typeof ApiPublicHooksCleanupLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/logs': {
      id: '/dev/logs'
      path: '/dev/logs'
      fullPath: '/dev/logs'
      preLoaderRoute: typeof DevLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scraper-logs/stream': {
      id: '/api/scraper-logs/stream'
      path: '/api/scraper-logs/stream'
      fullPath: '/api/scraper-logs/stream'
      preLoaderRoute: typeof ApiScraperLogsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/pdf': {
      id: '/api/reports/pdf'
      path: '/api/reports/pdf'
      fullPath: '/api/reports/pdf'
      preLoaderRoute: typeof ApiReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/auth': {
      id: '/api/dev/auth'
      path: '/api/dev/auth'
      fullPath: '/api/dev/auth'
      preLoaderRoute: typeof ApiDevAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-logs': {
      id: '/api/public/hooks/cleanup-logs'
      path: '/api/public/hooks/cleanup-logs'
      fullPath: '/api/public/hooks/cleanup-logs'
      preLoaderRoute: typeof ApiPublicHooksCleanupLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  DatabaseRoute: DatabaseRoute,
  JobsRoute: JobsRoute,
  RecordsRoute: RecordsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchlistRoute: WatchlistRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiVersionRoute: ApiVersionRoute,
  DevLogsRoute: DevLogsRoute,
  ApiDevAuthRoute: ApiDevAuthRoute,
  ApiReportsPdfRoute: ApiReportsPdfRoute,
  ApiScraperLogsStreamRoute: ApiScraperLogsStreamRoute,
  ApiPublicHooksCleanupLogsRoute: ApiPublicHooksCleanupLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
