// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let _initWarned = false;

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    if (!_initWarned) {
      console.warn("[supabase] Disabled — brakuje SUPABASE_URL lub SUPABASE_SERVICE_ROLE_KEY. Operacje DB zwrócą puste wyniki.");
      _initWarned = true;
    }
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// A chainable no-op query builder that returns { data: null, error: null }
// for any method chain (.select, .insert, .update, .delete, .eq, .order, etc.)
function createNoopBuilder(): any {
  const terminal = { data: null, error: null, count: 0 };
  const builder: any = new Proxy(Promise.resolve(terminal), {
    get(target, prop) {
      // Allow awaiting — return the thenable
      if (prop === 'then' || prop === 'catch' || prop === 'finally') {
        return (target as any)[prop].bind(target);
      }
      // Any chained method returns itself
      return (..._args: any[]) => builder;
    },
  });
  return builder;
}

// No-op Supabase client mock — every .from() returns a chainable no-op builder
function createNoopClient(): any {
  return new Proxy({}, {
    get(_target, prop) {
      if (prop === '__isNoopClient') return true;
      // .from() and any other method return a no-op builder
      return (..._args: any[]) => createNoopBuilder();
    },
  });
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as any, {
  get(_, prop, receiver) {
    if (prop === 'isAvailable') {
      if (_supabaseAdmin === undefined) _supabaseAdmin = createSupabaseAdminClient();
      return _supabaseAdmin !== null;
    }
    if (_supabaseAdmin === undefined) _supabaseAdmin = createSupabaseAdminClient();
    const client = _supabaseAdmin ?? createNoopClient();
    return Reflect.get(client, prop, receiver);
  },
});
